### ISSUE TITLE
Typo in pkg/feeds/README.md ?

### ISSUE THREAD

**Issue by lurch** [ossf/package-feeds#192]
The "**Poll npm every 10 minutes and crates every hour**" section of https://github.com/ossf/package-feeds/blob/main/pkg/feeds/README.md says:
```
feeds:
- type: npm
  options:
    poll_rate: "5m"
- type: crates
  options:
    poll_rate: "1h"
```
so it looks like there's a mismatch between "**every 10 minutes**" and `poll_rate: "5m"` ?
