### ISSUE TITLE
Contribute new publisher type

### ISSUE THREAD

**Issue by lukehinds** [ossf/package-feeds#422]
Hello,

I am interested in contributing a new publisher. This will essentially be a simple http client that will post published events to a configurable endpoint;

e.g...

```
publisher:
  type: 'http-client'
  config:
    http_client_config:
      url: 'http://127.0.0.1:8081/events'  # Replace with your actual URL
```

![image](https://github.com/ossf/package-feeds/assets/7058938/d2ddf2c2-bd51-45d5-a27e-7cc4a7191251)

I wanted to see what the communities appetite is before I rock up with a PR and no previous context. This will make feeds a key part of our platform and so on-going maintenance of the client will be a responsibility we are willing to take on for the long term.
